# Generated by Django 4.0.4 on 2022-05-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('notice_id', models.AutoField(primary_key=True, serialize=False)),
                ('notice_topic', models.CharField(max_length=45)),
                ('notice_content', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
