# Generated by Django 4.0.4 on 2022-05-12 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_course_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course_Details',
            new_name='Course_Detail',
        ),
    ]
