# Generated by Django 4.0.4 on 2022-05-13 09:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_rename_course_details_course_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=45)),
                ('phone', models.CharField(max_length=10)),
                ('your_query', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_designation', models.CharField(default='', max_length=100)),
                ('no_of_seats', models.IntegerField(default=0)),
                ('last_date_to_apply', models.DateField(default=django.utils.timezone.now)),
                ('posted_date', models.DateField(default=django.utils.timezone.now)),
                ('relpy_email', models.EmailField(default='', max_length=55)),
            ],
        ),
    ]
