# Generated by Django 4.0.4 on 2022-05-13 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_contact_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
