# Generated by Django 4.0.4 on 2022-05-24 09:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0008_user_feedback_rename_relpy_email_job_reply_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultancy',
            fields=[
                ('user_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('paasword', models.CharField(max_length=50)),
                ('name', models.CharField(default='', max_length=45)),
                ('email', models.EmailField(max_length=45)),
                ('phone', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=45)),
                ('address', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
