# Generated by Django 4.0.4 on 2022-05-31 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0010_administrativestaff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=45)),
                ('phone', models.CharField(max_length=10)),
                ('query', models.TextField()),
            ],
        ),
    ]
