# Generated by Django 4.0.4 on 2022-05-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_edit_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edit_profile',
            name='email',
            field=models.EmailField(default='', max_length=40),
        ),
    ]
