# Generated by Django 4.0.4 on 2022-05-24 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_edit_profile_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Edit_Profile',
        ),
    ]
